#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-hatchling
Version  : 0.22.0
Release  : 2
URL      : https://files.pythonhosted.org/packages/4c/45/5a72bb8b596c9cd3a433f4cf48622770d3d4114a7c9924b74c3ac247331e/hatchling-0.22.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/4c/45/5a72bb8b596c9cd3a433f4cf48622770d3d4114a7c9924b74c3ac247331e/hatchling-0.22.0.tar.gz
Summary  : Modern, extensible Python build backend
Group    : Development/Tools
License  : MIT
Requires: pypi-hatchling-bin = %{version}-%{release}
Requires: pypi-hatchling-license = %{version}-%{release}
Requires: pypi-hatchling-python = %{version}-%{release}
Requires: pypi-hatchling-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi-pathspec
BuildRequires : pypi-pluggy

%description
# Hatchling
-----
This is the extensible, standards compliant build backend used by [Hatch](https://github.com/ofek/hatch).

%package bin
Summary: bin components for the pypi-hatchling package.
Group: Binaries
Requires: pypi-hatchling-license = %{version}-%{release}

%description bin
bin components for the pypi-hatchling package.


%package license
Summary: license components for the pypi-hatchling package.
Group: Default

%description license
license components for the pypi-hatchling package.


%package python
Summary: python components for the pypi-hatchling package.
Group: Default
Requires: pypi-hatchling-python3 = %{version}-%{release}

%description python
python components for the pypi-hatchling package.


%package python3
Summary: python3 components for the pypi-hatchling package.
Group: Default
Requires: python3-core
Provides: pypi(hatchling)
Requires: pypi(editables)
Requires: pypi(packaging)
Requires: pypi(pathspec)
Requires: pypi(pluggy)
Requires: pypi(tomli)

%description python3
python3 components for the pypi-hatchling package.


%prep
%setup -q -n hatchling-0.22.0
cd %{_builddir}/hatchling-0.22.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649477443
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-hatchling
cp %{_builddir}/hatchling-0.22.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-hatchling/597acb03a5ab8ad933e0aa297418aa8e6ffe61b2
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/hatchling

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-hatchling/597acb03a5ab8ad933e0aa297418aa8e6ffe61b2

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
