#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-hatchling
Version  : 1.10.0
Release  : 24
URL      : https://files.pythonhosted.org/packages/3a/27/fe3419237a30e84f7ef8fd187770f09e3f689a406f078ecc3bf2056035ea/hatchling-1.10.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/3a/27/fe3419237a30e84f7ef8fd187770f09e3f689a406f078ecc3bf2056035ea/hatchling-1.10.0.tar.gz
Summary  : Modern, extensible Python build backend
Group    : Development/Tools
License  : MIT
Requires: pypi-hatchling-bin = %{version}-%{release}
Requires: pypi-hatchling-license = %{version}-%{release}
Requires: pypi-hatchling-python = %{version}-%{release}
Requires: pypi-hatchling-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi-pathspec
BuildRequires : pypi-pluggy

%description
# Hatchling
-----
This is the extensible, standards compliant build backend used by [Hatch](https://github.com/pypa/hatch).

%package bin
Summary: bin components for the pypi-hatchling package.
Group: Binaries
Requires: pypi-hatchling-license = %{version}-%{release}

%description bin
bin components for the pypi-hatchling package.


%package license
Summary: license components for the pypi-hatchling package.
Group: Default

%description license
license components for the pypi-hatchling package.


%package python
Summary: python components for the pypi-hatchling package.
Group: Default
Requires: pypi-hatchling-python3 = %{version}-%{release}

%description python
python components for the pypi-hatchling package.


%package python3
Summary: python3 components for the pypi-hatchling package.
Group: Default
Requires: python3-core
Provides: pypi(hatchling)
Requires: pypi(editables)
Requires: pypi(packaging)
Requires: pypi(pathspec)
Requires: pypi(pluggy)
Requires: pypi(tomli)

%description python3
python3 components for the pypi-hatchling package.


%prep
%setup -q -n hatchling-1.10.0
cd %{_builddir}/hatchling-1.10.0
pushd ..
cp -a hatchling-1.10.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1663600363
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-hatchling
cp %{_builddir}/hatchling-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-hatchling/597acb03a5ab8ad933e0aa297418aa8e6ffe61b2 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/hatchling

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-hatchling/597acb03a5ab8ad933e0aa297418aa8e6ffe61b2

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
